### ISSUE TITLE
maps issue

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/browser-template#17]
Ethan was attempting to look for a defined variable, he put a debugger in right after and it was show as not defined.  Web pack was uglyifying.  Console.log work, breakpoint worked, but debugger didn't work.  Doesn't work in chrome, works in safari, not in chrome canary.... Chrome bug?

**Comment by jrhorn424** [comment]
Fixed by acb0187b1dfeb91a0140bffccb95b7b0a94aa71b.

Leaving open for dicsussion.

Basically, Chrome doesn't like the [`eval` strategy](https://webpack.github.io/docs/configuration.html#devtool) of resolving original source. I think it might be related to the fact that Chrome has a [separate debugger scope](http://stackoverflow.com/questions/28388530/why-does-chrome-debugger-think-closed-local-variable-is-undefined) as an optimization. So even though `eval` works for translating compiled JS to original source lines, that **is not** the context in which the debugger eval's.

**Comment by Jcornmanhomonoff** [comment]
@gaand closing as obsolete
